export enum ServiceNames {
  FUND_CARD_CHARGE = 'FUND-CARD-CHARGE',
  MONEY_TRANSFER = 'MONEY-TRANSFER',
  PUBLIC_REPORTS = 'PUBLIC-REPORTS',
  BUSINESS_INTELLIGENCE_REPORT = 'BUSINESS-INTELLIGENCE-REPORT',
  CHEQUE_PICHAK = 'CHEQUE-PICHAK',
  BILLING = 'BILLING',
  CARTABLE = 'CARTABLE',
}

export const NUMBER_OF_SERVICES_SKELETONS = 7;
export const DEFAULT_NUMBER_OF_ANNOUNCEMENT_SKELETONS = 3;
