import React, { CSSProperties } from 'react';
import { BasicComponentProps } from '@ghased-portal/types';
export type BoxProps = BasicComponentProps & {
    children?: React.ReactNode;
    display?: CSSProperties['display'];
    flexDirection?: CSSProperties['flexDirection'];
    justifyContent?: CSSProperties['justifyContent'];
    alignItems?: CSSProperties['alignItems'];
    alignContent?: CSSProperties['alignContent'];
    gap?: CSSProperties['gap'];
    flexWrap?: CSSProperties['flexWrap'];
    flexGrow?: CSSProperties['flexGrow'];
    flexShrink?: CSSProperties['flexShrink'];
    flexBasis?: CSSProperties['flexBasis'];
    alignSelf?: CSSProperties['alignSelf'];
    height?: CSSProperties['height'];
    maxHeight?: CSSProperties['maxHeight'];
    minHeight?: CSSProperties['minHeight'];
    width?: CSSProperties['width'];
    maxWidth?: CSSProperties['maxWidth'];
    minWidth?: CSSProperties['minWidth'];
    padding?: CSSProperties['padding'];
    paddingTop?: CSSProperties['paddingTop'];
    paddingRight?: CSSProperties['paddingRight'];
    paddingBottom?: CSSProperties['paddingBottom'];
    paddingLeft?: CSSProperties['paddingLeft'];
    margin?: CSSProperties['margin'];
    marginTop?: CSSProperties['marginTop'];
    marginRight?: CSSProperties['marginRight'];
    marginBottom?: CSSProperties['marginBottom'];
    marginLeft?: CSSProperties['marginLeft'];
    border?: CSSProperties['border'];
    borderTop?: CSSProperties['borderTop'];
    borderRight?: CSSProperties['borderRight'];
    borderBottom?: CSSProperties['borderBottom'];
    borderLeft?: CSSProperties['borderLeft'];
    borderRadius?: CSSProperties['borderRadius'];
    boxShadow?: CSSProperties['boxShadow'];
    backgroundColor?: CSSProperties['backgroundColor'];
    color?: CSSProperties['color'];
    fontSize?: CSSProperties['fontSize'];
    fontWeight?: CSSProperties['fontWeight'];
    lineHeight?: CSSProperties['lineHeight'];
    letterSpacing?: CSSProperties['letterSpacing'];
    textAlign?: CSSProperties['textAlign'];
    fillChildren?: boolean;
    visible?: boolean;
};
export declare const Box: React.FC<BoxProps>;
//# sourceMappingURL=box.d.ts.map